apiVersion: v1
kind: Service
metadata:
  name: mywebapp-deploy-service
  labels:
    app: mywebapp
spec:
  type: NodePort
  selector:
    app: mywebapp
  ports:
    - port: 8082
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      name: mywebapp-pod
      labels:
        app: mywebapp
    spec:
      containers:
        - name: mywebapp
          image: sripadaani/makerapp-v2:1
          ports:
            - containerPort: 80

